### ISSUE TITLE
Thompson Issue

### ISSUE THREAD

**Issue by americanhawk1** [S3ctor/Rust-Recoil-Script-Cpp#5]
I know that you might not care enough to respond, but I have an issue that's been bugging me while implementing one of the things from your source, and that's the Thompson view angles. This issue isn't just with my source, the same exact problem occurs in your exact source after testing.

The problem is that the Thompson view angles seem to be REALLY large compared to the other view angles. I've noticed that they're the exact same angles that are in one of the Rust dump's I've seen from last year. In this dump, the values for every gun is large, but it's seems that you've converted them somehow into smaller values before implementing them into your source; all of the values but the Thompson.

Is there an explanation for this? It's really been bugging me and I'm having trouble coming up with an algorithm that's accurate enough to use.

**Comment by S3ctor** [comment]
You'll need to reverse how the game handles the weapon FoV factors when constructing a recoil trajectory; consensus is that the thompson and custom have different base FoV and the calculation in this recoil script doesn't factor in the weapon FoV although it works perfectly for all the other weapons
